name: Move new issues into Triage

on:
  issues:
    types: [opened]:
  pull_request:
    types: [opened]

jobs:
  add-to-todo:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.5.1
        with:
          project: Basic board
          column: Todo
          repo-token: ${{ secrets.GITHUB_TOKEN }}
